name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master

env:
    FORCE_COLOR: 2
    NODE: 16

permissions:
    contents: read

jobs:
    pages:
        permissions:
            contents: write # for peaceiris/actions-gh-pages to push pages branch
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
            - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
              with:
                  node-version: "${{ env.NODE }}"
                  cache: "npm"
            - run: npm ci
            - name: Build docs
              run: npm run build:docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
