name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master

env:
    FORCE_COLOR: 2
    NODE: 16

permissions:
    contents: read

jobs:
    pages:
        permissions:
            contents: write # for peaceiris/actions-gh-pages to push pages branch
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
            - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
              with:
                  node-version: "${{ env.NODE }}"
                  cache: "npm"
            - run: npm ci
            - name: Build docs
              run: npm run build:docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
